
- name: Ensure py-lxml is installed
  package:
    name: py-lxml
    state: present

- name: Place ssh keys
  copy:
    src: "{{ item.file }}"
    dest: ~/.ssh/
    owner: 1000
    group: 1000
    mode: "{{ item.mode }}"
  loop:
    - { file: "id_rsa_demo",     mode: "0600" }
    - { file: "id_rsa_demo.pub", mode: "0644" }

- name: Create ssh config directory
  file:
    state: directory
    path: ~/.ssh/conf.d
    owner: 1000
    group: 1000
    mode: 0755

- name: Place ssh config
  template:
    src: ssh_config
    dest: ~/.ssh/config
    owner: 1000
    group: 1000
    mode: 0644
